import java.util.Scanner;
import java.text.DecimalFormat;
/** This program will compute the value generated by a specified
*expression.
*
*Nathan Adkins COMP - 1210 - 001
*9/11/19
*/ 
public class EvalExpression {
/**User inputs variable to be evaluated by program.
*@param args Command line arguments - not used*/
   public static void main(String [] args) {
   
      double x = 0; 
      double result = 0; 
      double sqrRoot = 0; 
      int locationLeft = 0;
      int locationRight = 0;
      String resultString = (""); 
      Scanner userInput = new Scanner(System.in);
      System.out.print("Enter a value for x: ");
      x = userInput.nextDouble();
      sqrRoot = Math.sqrt(Math.abs(2.6 * Math.pow(x, 5) - 6.8 * x + 7)); 
      result = ((12.4 * Math.pow(x, 6) - 1.2 * Math.pow(x, 3) + sqrRoot) 
         / (Math.pow(x, 4) + 9)); 
      System.out.print("Result: ");
      System.out.println(result);
      resultString = Double.toString(result);
      locationLeft = resultString.indexOf(".");
      System.out.print("# of characters to left of decimal point: ");
      System.out.println(locationLeft);
      locationRight = resultString.length() - 1;
      locationRight = locationRight - locationLeft;
      System.out.print("# of characters to right of decimal point: ");
      System.out.println(locationRight);
      DecimalFormat df = new DecimalFormat("#,##0.0###");
      System.out.print("Formatted Result: ");
      System.out.println(df.format(result));
   }
   
}